/**
 * WindyMap Component
 * Displays the Windy.com weather forecast map using WebView
 * Copied from FishTopia - uses embed URL approach
 */

import React, { useState, useRef } from 'react';
import {
  View,
  StyleSheet,
  TouchableOpacity,
  Text,
  ActivityIndicator,
  Dimensions,
  ScrollView,
} from 'react-native';
import { WebView } from 'react-native-webview';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

// Windy.com API key (from FishTopia)
const WINDY_API_KEY = 'N44TdWVw8Y6KsyOAjSGqnkiRWpnO9M3z';

// Alaska center coordinates
const ALASKA_LAT = 61.2;
const ALASKA_LON = -149.9;
const DEFAULT_ZOOM = 5;

interface WindyMapProps {
  visible: boolean;
  onClose?: () => void;
  latitude?: number;
  longitude?: number;
  embedded?: boolean; // If true, renders without header/close button
}

// Quick access overlay options with descriptions
const OVERLAY_OPTIONS: { id: string; label: string; title: string; description: string }[] = [
  { 
    id: 'wind', 
    label: 'Wind',
    title: 'Wind Speed & Direction',
    description: 'Shows wind speed (in knots) and direction at the surface. Colors indicate speed: blue/green = light, yellow/orange = moderate, red/purple = strong. Arrows show direction the wind is blowing TO.'
  },
  { 
    id: 'waves', 
    label: 'Waves',
    title: 'Significant Wave Height (Combined)',
    description: 'The TOTAL wave height combining all sources - both local wind waves AND swell from distant storms. This is what you\'ll actually experience on the water. Measured as "significant wave height" (average of the highest 1/3 of waves).'
  },
  { 
    id: 'swell', 
    label: 'Swell',
    title: 'Swell Waves',
    description: 'Waves generated by DISTANT storms that have traveled to your area. These are long-period, smooth, organized "rolling" waves. You can have big swell on a calm, windless day. Great for understanding underlying sea state.'
  },
  { 
    id: 'swell1', 
    label: 'Swell 1',
    title: 'Primary Swell',
    description: 'The dominant swell direction and height. This is the main swell train affecting the area, usually from the largest or closest storm system.'
  },
  { 
    id: 'swell2', 
    label: 'Swell 2',
    title: 'Secondary Swell',
    description: 'A second swell train from a different direction, if present. When two swells combine, it can create confused, uncomfortable seas even if each individual swell is moderate.'
  },
  { 
    id: 'wwaves', 
    label: 'Wind Waves',
    title: 'Wind Waves (Local)',
    description: 'Waves generated ONLY by local wind blowing on the water surface. These are typically shorter period, choppier, and more irregular than swell. Directly tied to current wind conditions - when wind dies, these fade quickly.'
  },
  { 
    id: 'currents', 
    label: 'Currents',
    title: 'Ocean Currents',
    description: 'Shows the speed and direction of ocean surface currents. Important for navigation, drift fishing, and understanding water movement. Note: This shows ocean currents, not tidal currents which vary with tide cycles.'
  },
  { 
    id: 'sst', 
    label: 'Sea Temp',
    title: 'Sea Surface Temperature',
    description: 'Water temperature at the surface in °F. Useful for finding temperature breaks where fish congregate, understanding fog potential, and general conditions. Warmer water = red/orange, colder = blue/purple.'
  },
];

const WindyMap: React.FC<WindyMapProps> = ({
  visible,
  onClose,
  latitude = ALASKA_LAT,
  longitude = ALASKA_LON,
  embedded = false,
}) => {
  const insets = useSafeAreaInsets();
  const webViewRef = useRef<any>(null);
  const [loading, setLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);
  const [activeOverlay, setActiveOverlay] = useState('wind');
  const [showInfo, setShowInfo] = useState(false);
  
  // Get current overlay info
  const currentOverlayInfo = OVERLAY_OPTIONS.find(o => o.id === activeOverlay);

  if (!visible) return null;

  // Windy embed URL with parameters - EXACTLY like FishTopia (no API key in URL)
  const windyUrl = `https://embed.windy.com/embed2.html?lat=${latitude}&lon=${longitude}&zoom=${DEFAULT_ZOOM}&level=surface&overlay=${activeOverlay}&product=ecmwf&menu=false&message=false&marker=false&calendar=now&pressure=false&type=map&location=coordinates&metricWind=kt&metricTemp=%C2%B0F&radarRange=-1`;
  
  // Handle overlay change
  const handleOverlayChange = (overlayId: string) => {
    setActiveOverlay(overlayId);
    setRefreshKey(prev => prev + 1);
  };

  const containerStyle = embedded
    ? styles.containerEmbedded
    : [styles.containerFullscreen, { paddingTop: insets.top }];

  return (
    <View style={containerStyle}>
      {/* Header - only show if not embedded */}
      {!embedded && (
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Weather Forecast</Text>
          <View style={styles.headerButtons}>
            <TouchableOpacity
              style={styles.headerButton}
              onPress={() => setShowInfo(true)}
            >
              <Text style={styles.headerButtonText}>ℹ️</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.headerButton}
              onPress={() => setRefreshKey(prev => prev + 1)}
            >
              <Text style={styles.headerButtonText}>↺</Text>
            </TouchableOpacity>
            {onClose && (
              <TouchableOpacity style={styles.headerButton} onPress={onClose}>
                <Text style={styles.headerButtonText}>✕</Text>
              </TouchableOpacity>
            )}
          </View>
        </View>
      )}
      
      {/* Overlay Quick Access Buttons */}
      <ScrollView 
        horizontal 
        showsHorizontalScrollIndicator={false}
        style={styles.overlayBar}
        contentContainerStyle={styles.overlayBarContent}
      >
        {OVERLAY_OPTIONS.map((option) => (
          <TouchableOpacity
            key={option.id}
            style={[
              styles.overlayButton,
              activeOverlay === option.id && styles.overlayButtonActive
            ]}
            onPress={() => handleOverlayChange(option.id)}
          >
            <Text style={[
              styles.overlayButtonText,
              activeOverlay === option.id && styles.overlayButtonTextActive
            ]}>
              {option.label}
            </Text>
          </TouchableOpacity>
        ))}
      </ScrollView>

      {/* WebView with Windy map */}
      <View style={styles.webviewContainer}>
        {loading && (
          <View style={styles.loadingOverlay}>
            <ActivityIndicator size="large" color="#4FC3F7" />
            <Text style={styles.loadingText}>Loading weather map...</Text>
          </View>
        )}
        <WebView
          key={refreshKey}
          ref={webViewRef}
          source={{ uri: windyUrl }}
          style={styles.webview}
          onLoadStart={() => setLoading(true)}
          onLoadEnd={() => setLoading(false)}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={false}
          scalesPageToFit={true}
          injectedJavaScript={`
            // Hide Windy's menu and detail elements for a clean map view
            const style = document.createElement('style');
            style.textContent = \`
              #menu-wrapper, .menu-wrapper, #bottom, .bottom,
              #mobile-ovr-select, .mobile-ovr-select,
              #plugins, .plugins, #rh-bottom, .rh-bottom,
              .leaflet-control-container, #detail,
              .overlay-select, #overlay-select { 
                display: none !important; 
              }
              #map-container { 
                bottom: 0 !important; 
              }
            \`;
            document.head.appendChild(style);
            true;
          `}
        />
      </View>

      {/* Legend */}
      <View style={styles.legend}>
        <Text style={styles.legendText}>Powered by Windy.com</Text>
      </View>
      
      {/* Info Modal */}
      {showInfo && currentOverlayInfo && (
        <TouchableOpacity 
          style={styles.infoOverlay} 
          activeOpacity={1}
          onPress={() => setShowInfo(false)}
        >
          <View style={styles.infoModal}>
            <View style={styles.infoHeader}>
              <Text style={styles.infoTitle}>{currentOverlayInfo.title}</Text>
              <TouchableOpacity onPress={() => setShowInfo(false)}>
                <Text style={styles.infoCloseButton}>✕</Text>
              </TouchableOpacity>
            </View>
            <Text style={styles.infoDescription}>{currentOverlayInfo.description}</Text>
            
            <View style={styles.infoTip}>
              <Text style={styles.infoTipLabel}>Tip</Text>
              <Text style={styles.infoTipText}>
                Tap the refresh button to reset the map if the detail panel covers the legend.
              </Text>
            </View>
          </View>
        </TouchableOpacity>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  containerEmbedded: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  containerFullscreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#1a1a2e',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#16213e',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFF',
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  headerButton: {
    padding: 4,
  },
  headerButtonText: {
    fontSize: 20,
    color: '#FFF',
  },
  webviewContainer: {
    flex: 1,
    backgroundColor: '#0a0a1a',
  },
  webview: {
    flex: 1,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0a0a1a',
    zIndex: 10,
  },
  loadingText: {
    marginTop: 12,
    color: '#4FC3F7',
    fontSize: 14,
  },
  legend: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#16213e',
    alignItems: 'center',
  },
  legendText: {
    fontSize: 11,
    color: '#888',
  },
  overlayBar: {
    backgroundColor: '#1a1a2e',
    maxHeight: 44,
  },
  overlayBarContent: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 8,
    flexDirection: 'row',
  },
  overlayButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  overlayButtonActive: {
    backgroundColor: '#4FC3F7',
    borderColor: '#4FC3F7',
  },
  overlayButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
  },
  overlayButtonTextActive: {
    color: '#000',
  },
  infoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    zIndex: 100,
  },
  infoModal: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 20,
    maxWidth: 400,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(79, 195, 247, 0.3)',
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4FC3F7',
    flex: 1,
    marginRight: 12,
  },
  infoCloseButton: {
    fontSize: 24,
    color: '#FFF',
  },
  infoDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: '#DDD',
  },
  infoTip: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  infoTipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFD54F',
    marginBottom: 4,
  },
  infoTipText: {
    fontSize: 13,
    color: '#AAA',
    lineHeight: 18,
  },
});

export default WindyMap;
