#!/usr/bin/env python3
"""
Generate cloud-functions/generators-base/config.py from config/regions.json.

This is the build-time codegen step that ensures the Python tile generators
always use the same region data as the master config. Run this before building
any generator Docker images.

Usage:
    python scripts/generate-config-py.py [--output PATH]
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
REGIONS_JSON = os.path.join(PROJECT_ROOT, 'config', 'regions.json')
DEFAULT_OUTPUT = os.path.join(
    PROJECT_ROOT, 'cloud-functions', 'generators-base', 'config.py'
)


def load_regions(path):
    with open(path, 'r') as f:
        data = json.load(f)
    return data['regions']


def normalize_bounds(bounds):
    """Normalize bounds to always be a list of dicts."""
    if isinstance(bounds, list):
        return bounds
    return [bounds]


def generate(regions):
    lines = []

    lines.append('# AUTO-GENERATED from config/regions.json -- DO NOT EDIT')
    lines.append('# Regenerate with: python scripts/generate-config-py.py')
    lines.append('"""')
    lines.append('Centralized configuration for all XNautical imagery generators.')
    lines.append('')
    lines.append('Generated from config/regions.json. Do not edit this file directly;')
    lines.append('edit regions.json and re-run scripts/generate-config-py.py instead.')
    lines.append('"""')
    lines.append('')
    lines.append('import os')
    lines.append('')
    lines.append("BUCKET_NAME = os.environ.get('STORAGE_BUCKET', 'xnautical-8a296.firebasestorage.app')")
    lines.append('')

    # DISTRICT_PREFIXES
    lines.append("# App-side filename prefixes per district (must match app's DISTRICT_PREFIXES)")
    lines.append('DISTRICT_PREFIXES = {')
    items = list(regions.items())
    for i in range(0, len(items), 2):
        chunk = items[i:i + 2]
        parts = [f"'{rid}': '{r['prefix']}'" for rid, r in chunk]
        lines.append('    ' + ', '.join(parts) + ',')
    lines.append('}')
    lines.append('')

    # BASEMAP_FILENAMES
    lines.append('# Basemap filenames derived from district prefixes')
    lines.append("BASEMAP_FILENAMES = {k: f'{v}_basemap' for k, v in DISTRICT_PREFIXES.items()}")
    lines.append('')

    # REGION_BOUNDS
    lines.append('# Region bounds definitions')
    lines.append('REGION_BOUNDS = {')
    for rid, r in regions.items():
        bounds_list = normalize_bounds(r['bounds'])
        lines.append(f"    '{rid}': {{'name': {repr(r['name'])}, 'bounds': [")
        for b in bounds_list:
            lines.append(
                f"        {{'west': {b['west']}, 'south': {b['south']}, "
                f"'east': {b['east']}, 'north': {b['north']}}},"
            )
        lines.append('    ]},')
    lines.append('}')
    lines.append('')

    # Zoom packs (static, not from regions.json)
    lines.append('# Standard zoom packs: z0-5 combined, then z6..z14 individually')
    lines.append('# Used by basemap, ocean, terrain generators')
    lines.append('STANDARD_ZOOM_PACKS = {')
    lines.append("    'z0-5':  {'minZoom': 0,  'maxZoom': 5},")
    for z in range(6, 15):
        lines.append(f"    'z{z}':{' ' * (4 - len(str(z)))}  {{'minZoom': {z}, {' ' if z < 10 else ''}'maxZoom': {z}}},")
    lines.append('}')
    lines.append('')

    lines.append('# Satellite uses different zoom groupings (z6-7 combined)')
    lines.append('SATELLITE_ZOOM_PACKS = {')
    lines.append("    'z0-5':  {'minZoom': 0,  'maxZoom': 5},")
    lines.append("    'z6-7':  {'minZoom': 6,  'maxZoom': 7},")
    for z in range(8, 15):
        lines.append(f"    'z{z}':{' ' * (4 - len(str(z)))}  {{'minZoom': {z}, {' ' if z < 10 else ''}'maxZoom': {z}}},")
    lines.append('}')
    lines.append('')
    lines.append('')

    # Helper functions
    lines.append('def get_district_prefix(region_id: str) -> str:')
    lines.append('    """Get the app-side filename prefix for a district."""')
    lines.append('    if region_id in DISTRICT_PREFIXES:')
    lines.append('        return DISTRICT_PREFIXES[region_id]')
    lines.append("    raise ValueError(f'Unknown region_id: {region_id}. Add it to config/regions.json.')")
    lines.append('')
    lines.append('')
    lines.append('def get_basemap_filename(region_id: str) -> str:')
    lines.append('    """Get the basemap filename (without extension) for a district."""')
    lines.append("    return BASEMAP_FILENAMES.get(region_id, f'{get_district_prefix(region_id)}_basemap')")
    lines.append('')
    lines.append('')
    lines.append('import threading')
    lines.append('_config_lock = threading.Lock()')
    lines.append('')
    lines.append('')
    lines.append('def register_custom_region(region_id, bounds, name=None):')
    lines.append('    """Register an ad-hoc region from a /generate request body (thread-safe)."""')
    lines.append('    bounds_list = [bounds] if isinstance(bounds, dict) else bounds')
    lines.append('    with _config_lock:')
    lines.append('        REGION_BOUNDS[region_id] = {')
    lines.append("            'name': name or region_id,")
    lines.append("            'bounds': bounds_list,")
    lines.append('        }')
    lines.append('        if region_id not in DISTRICT_PREFIXES:')
    lines.append("            DISTRICT_PREFIXES[region_id] = region_id.replace('cgd', '').lower()")
    lines.append("            BASEMAP_FILENAMES[region_id] = f'{DISTRICT_PREFIXES[region_id]}_basemap'")
    lines.append('')

    return '\n'.join(lines)


def main():
    output_path = DEFAULT_OUTPUT

    args = sys.argv[1:]
    if '--output' in args:
        idx = args.index('--output')
        if idx + 1 < len(args):
            output_path = args[idx + 1]

    if not os.path.exists(REGIONS_JSON):
        print(f'Error: {REGIONS_JSON} not found', file=sys.stderr)
        sys.exit(1)

    regions = load_regions(REGIONS_JSON)
    content = generate(regions)

    with open(output_path, 'w') as f:
        f.write(content)

    print(f'Generated {output_path} from {REGIONS_JSON} ({len(regions)} regions)')


if __name__ == '__main__':
    main()
