# AUTO-GENERATED from config/regions.json -- DO NOT EDIT
# Regenerate with: python scripts/generate-config-py.py
"""
Centralized configuration for all XNautical imagery generators.

Generated from config/regions.json. Do not edit this file directly;
edit regions.json and re-run scripts/generate-config-py.py instead.
"""

import os

BUCKET_NAME = os.environ.get('STORAGE_BUCKET', 'xnautical-8a296.firebasestorage.app')

# App-side filename prefixes per district (must match app's DISTRICT_PREFIXES)
DISTRICT_PREFIXES = {
    '01cgd': 'd01', '05cgd': 'd05',
    '07cgd': 'd07', '08cgd': 'd08',
    '09cgd': 'd09', '11cgd': 'd11',
    '13cgd': 'd13', '14cgd': 'd14',
    '17cgd': 'd17', '17cgd-Juneau': '17-juneau',
    '17cgd-Anchorage': '17-anchorage', '17cgd-Kodiak': '17-kodiak',
    '17cgd-DutchHarbor': '17-dutchharbor', '17cgd-Nome': '17-nome',
    '17cgd-Barrow': '17-barrow', '07cgd-wflorida': '07-wflorida',
    '17cgd-test': '17-test',
}

# Basemap filenames derived from district prefixes
BASEMAP_FILENAMES = {k: f'{v}_basemap' for k, v in DISTRICT_PREFIXES.items()}

# Region bounds definitions
REGION_BOUNDS = {
    '01cgd': {'name': 'Northeast', 'bounds': [
        {'west': -76, 'south': 39, 'east': -65, 'north': 48},
    ]},
    '05cgd': {'name': 'East', 'bounds': [
        {'west': -82, 'south': 32, 'east': -72, 'north': 42},
    ]},
    '07cgd': {'name': 'Southeast', 'bounds': [
        {'west': -85, 'south': 23, 'east': -63, 'north': 35},
    ]},
    '08cgd': {'name': 'Heartland', 'bounds': [
        {'west': -100, 'south': 23, 'east': -80, 'north': 33},
    ]},
    '09cgd': {'name': 'Great Lakes', 'bounds': [
        {'west': -94, 'south': 40, 'east': -75, 'north': 50},
    ]},
    '11cgd': {'name': 'Southwest', 'bounds': [
        {'west': -126, 'south': 30, 'east': -114, 'north': 39},
    ]},
    '13cgd': {'name': 'Northwest', 'bounds': [
        {'west': -130, 'south': 33, 'east': -119, 'north': 50},
    ]},
    '14cgd': {'name': 'Oceania', 'bounds': [
        {'west': -162, 'south': 17, 'east': -153, 'north': 24},
    ]},
    '17cgd': {'name': 'All Alaska', 'bounds': [
        {'west': -180, 'south': 50, 'east': -129, 'north': 72},
        {'west': 170, 'south': 50, 'east': 180, 'north': 65},
    ]},
    '17cgd-Juneau': {'name': 'Southeast Alaska', 'bounds': [
        {'west': -145.5, 'south': 54.5, 'east': -130, 'north': 61},
    ]},
    '17cgd-Anchorage': {'name': 'Southcentral Alaska', 'bounds': [
        {'west': -157, 'south': 56, 'east': -140, 'north': 62},
    ]},
    '17cgd-Kodiak': {'name': 'Southwest Alaska', 'bounds': [
        {'west': -168, 'south': 54, 'east': -150, 'north': 60},
    ]},
    '17cgd-DutchHarbor': {'name': 'Aleutians', 'bounds': [
        {'west': -180, 'south': 51, 'east': -164, 'north': 60},
        {'west': 170, 'south': 51, 'east': 180, 'north': 56},
    ]},
    '17cgd-Nome': {'name': 'Western Alaska', 'bounds': [
        {'west': -176, 'south': 59, 'east': -158, 'north': 67},
    ]},
    '17cgd-Barrow': {'name': 'Arctic Alaska', 'bounds': [
        {'west': -170, 'south': 65, 'east': -140, 'north': 72},
    ]},
    '07cgd-wflorida': {'name': 'W. Florida', 'bounds': [
        {'west': -83.448076, 'south': 27.398773, 'east': -82.063799, 'north': 28.33599},
    ]},
    '17cgd-test': {'name': 'Arctic (Test)', 'bounds': [
        {'west': -153.6, 'south': 57.6, 'east': -144, 'north': 62.4},
    ]},
}

# Standard zoom packs: z0-5 combined, then z6..z14 individually
# Used by basemap and terrain generators
STANDARD_ZOOM_PACKS = {
    'z0-5':  {'minZoom': 0,  'maxZoom': 5},
    'z6':     {'minZoom': 6,  'maxZoom': 6},
    'z7':     {'minZoom': 7,  'maxZoom': 7},
    'z8':     {'minZoom': 8,  'maxZoom': 8},
    'z9':     {'minZoom': 9,  'maxZoom': 9},
    'z10':    {'minZoom': 10, 'maxZoom': 10},
    'z11':    {'minZoom': 11, 'maxZoom': 11},
    'z12':    {'minZoom': 12, 'maxZoom': 12},
    'z13':    {'minZoom': 13, 'maxZoom': 13},
    'z14':    {'minZoom': 14, 'maxZoom': 14},
}

# Ocean capped at z12 (z13-14 ocean tiles are massive and unnecessary)
OCEAN_ZOOM_PACKS = {
    'z0-5':  {'minZoom': 0,  'maxZoom': 5},
    'z6':     {'minZoom': 6,  'maxZoom': 6},
    'z7':     {'minZoom': 7,  'maxZoom': 7},
    'z8':     {'minZoom': 8,  'maxZoom': 8},
    'z9':     {'minZoom': 9,  'maxZoom': 9},
    'z10':    {'minZoom': 10, 'maxZoom': 10},
    'z11':    {'minZoom': 11, 'maxZoom': 11},
    'z12':    {'minZoom': 12, 'maxZoom': 12},
}

# Satellite uses different zoom groupings (z6-7 combined)
SATELLITE_ZOOM_PACKS = {
    'z0-5':  {'minZoom': 0,  'maxZoom': 5},
    'z6-7':  {'minZoom': 6,  'maxZoom': 7},
    'z8':     {'minZoom': 8,  'maxZoom': 8},
    'z9':     {'minZoom': 9,  'maxZoom': 9},
    'z10':    {'minZoom': 10, 'maxZoom': 10},
    'z11':    {'minZoom': 11, 'maxZoom': 11},
    'z12':    {'minZoom': 12, 'maxZoom': 12},
    'z13':    {'minZoom': 13, 'maxZoom': 13},
    'z14':    {'minZoom': 14, 'maxZoom': 14},
}


def get_district_prefix(region_id: str) -> str:
    """Get the app-side filename prefix for a district."""
    if region_id in DISTRICT_PREFIXES:
        return DISTRICT_PREFIXES[region_id]
    raise ValueError(f'Unknown region_id: {region_id}. Add it to config/regions.json.')


def get_basemap_filename(region_id: str) -> str:
    """Get the basemap filename (without extension) for a district."""
    return BASEMAP_FILENAMES.get(region_id, f'{get_district_prefix(region_id)}_basemap')


import threading
_config_lock = threading.Lock()


def register_custom_region(region_id, bounds, name=None):
    """Register an ad-hoc region from a /generate request body (thread-safe)."""
    bounds_list = [bounds] if isinstance(bounds, dict) else bounds
    with _config_lock:
        REGION_BOUNDS[region_id] = {
            'name': name or region_id,
            'bounds': bounds_list,
        }
        if region_id not in DISTRICT_PREFIXES:
            DISTRICT_PREFIXES[region_id] = region_id.replace('cgd', '').lower()
            BASEMAP_FILENAMES[region_id] = f'{DISTRICT_PREFIXES[region_id]}_basemap'
